#!/usr/bin/env python3
"""
generate_pdf.py — Render an AISO audit Markdown report to a Sumvec-branded PDF.

Usage:
    python generate_pdf.py <path-to-audit.md> [--out <path>] [--logo <path>] [--target-url <url>]

Output:
    By default, writes the PDF next to the input file with the filename pattern
    <host>-<YYYY-MM-DD>-<HHMM>.pdf, where <host> is derived from --target-url if
    provided, or parsed out of the input filename otherwise.

Dependencies:
    weasyprint, markdown
        pip install weasyprint markdown

If weasyprint is missing, the script prints an install instruction and exits 0
so it never blocks the rest of the audit run.

Branding:
    Reads the bundled `assets/sumvec-logo.svg` (sits in the same skill bundle,
    one directory above `scripts/`). Brand palette from BRAND_GUIDE.md:
        Sumvec Blue   #00A5E0
        Sumvec Orange #FF8101
        Dark Navy     #1E2A3A
        Warm Gray     #808080
"""

from __future__ import annotations

import argparse
import datetime as dt
import re
import sys
from pathlib import Path
from urllib.parse import urlparse


SUMVEC_BLUE = "#00A5E0"
SUMVEC_ORANGE = "#FF8101"
DARK_NAVY = "#1E2A3A"
WARM_GRAY = "#808080"


def _missing_deps_message() -> str:
    return (
        "[generate_pdf] weasyprint / markdown not installed — skipping PDF generation.\n"
        "[generate_pdf] To enable PDF output: pip install weasyprint markdown\n"
        "[generate_pdf] The Markdown audit report has still been written; you can\n"
        "[generate_pdf] re-run this script after installing the dependencies."
    )


def _sanitize_host(host: str) -> str:
    return re.sub(r"[^a-z0-9-]", "-", host.lower()).strip("-")


def _derive_host_from_filename(md_path: Path) -> str:
    # Existing filename pattern: aiso-audit-<host>-<YYYY-MM-DD>.md
    name = md_path.stem  # strips .md
    m = re.match(r"aiso-audit-(.+)-(\d{4}-\d{2}-\d{2})$", name)
    if m:
        return m.group(1)
    return _sanitize_host(name)


def _host_from_url(url: str) -> str:
    parsed = urlparse(url if "://" in url else f"https://{url}")
    return _sanitize_host(parsed.netloc or url)


def _resolve_logo_path(script_path: Path, override: str | None) -> Path | None:
    if override:
        p = Path(override).expanduser().resolve()
        return p if p.exists() else None
    default = script_path.parent.parent / "assets" / "sumvec-logo.svg"
    return default if default.exists() else None


def _build_html(
    md_text: str,
    target_url: str,
    generated_at: dt.datetime,
    logo_data_uri: str | None,
) -> str:
    import markdown as md_lib

    body_html = md_lib.markdown(
        md_text,
        extensions=["tables", "fenced_code", "toc", "sane_lists"],
    )

    logo_block = (
        f'<img class="logo" src="{logo_data_uri}" alt="Sumvec.AI" />'
        if logo_data_uri
        else '<div class="logo-text">sumvec<span>.AI</span></div>'
    )

    css = f"""
    @page {{
        size: A4;
        margin: 22mm 18mm 22mm 18mm;
        @top-left {{
            content: "AI Search Optimization Audit";
            font-family: 'Inter', 'Helvetica Neue', Arial, sans-serif;
            font-size: 8.5pt;
            color: {WARM_GRAY};
            padding-top: 6mm;
        }}
        @top-right {{
            content: "sumvec.ai";
            font-family: 'Inter', 'Helvetica Neue', Arial, sans-serif;
            font-size: 8.5pt;
            color: {SUMVEC_BLUE};
            font-weight: 600;
            padding-top: 6mm;
        }}
        @bottom-left {{
            content: "Generated by ai-search-optimization · Sumvec.AI";
            font-family: 'Inter', 'Helvetica Neue', Arial, sans-serif;
            font-size: 7.5pt;
            color: {WARM_GRAY};
            padding-bottom: 6mm;
        }}
        @bottom-right {{
            content: counter(page) " / " counter(pages);
            font-family: 'Inter', 'Helvetica Neue', Arial, sans-serif;
            font-size: 7.5pt;
            color: {WARM_GRAY};
            padding-bottom: 6mm;
        }}
    }}
    @page :first {{
        margin: 0;
        @top-left {{ content: none; }}
        @top-right {{ content: none; }}
        @bottom-left {{ content: none; }}
        @bottom-right {{ content: none; }}
    }}

    html, body {{
        font-family: 'Inter', 'Helvetica Neue', Arial, sans-serif;
        font-size: 10.5pt;
        line-height: 1.55;
        color: {DARK_NAVY};
        margin: 0;
        padding: 0;
    }}

    /* Cover */
    .cover {{
        page: cover;
        background: {DARK_NAVY};
        color: #ffffff;
        height: 297mm;
        width: 210mm;
        padding: 28mm 22mm 22mm 22mm;
        box-sizing: border-box;
        position: relative;
        page-break-after: always;
    }}
    .cover .logo {{
        height: 36px;
        margin-bottom: 24mm;
    }}
    .cover .logo-text {{
        font-size: 24pt;
        font-weight: 800;
        color: {SUMVEC_BLUE};
        margin-bottom: 24mm;
    }}
    .cover .logo-text span {{
        color: {WARM_GRAY};
        font-size: 14pt;
        vertical-align: super;
    }}
    .cover .eyebrow {{
        font-size: 10pt;
        text-transform: uppercase;
        letter-spacing: 0.18em;
        color: {SUMVEC_ORANGE};
        font-weight: 600;
        margin-bottom: 4mm;
    }}
    .cover h1.title {{
        font-size: 32pt;
        font-weight: 800;
        line-height: 1.15;
        color: #ffffff;
        margin: 0 0 6mm 0;
        letter-spacing: -0.01em;
    }}
    .cover .target {{
        font-size: 14pt;
        font-weight: 600;
        color: {SUMVEC_BLUE};
        word-break: break-all;
        margin-bottom: 18mm;
    }}
    .cover .meta {{
        position: absolute;
        bottom: 22mm;
        left: 22mm;
        right: 22mm;
        font-size: 10pt;
        color: rgba(255, 255, 255, 0.78);
        border-top: 1px solid rgba(0, 165, 224, 0.4);
        padding-top: 6mm;
    }}
    .cover .meta .row {{
        display: flex;
        justify-content: space-between;
        margin-bottom: 2mm;
    }}
    .cover .meta .label {{
        color: {WARM_GRAY};
        text-transform: uppercase;
        letter-spacing: 0.12em;
        font-size: 8pt;
    }}
    .cover .accent-bar {{
        position: absolute;
        top: 0; left: 0; right: 0;
        height: 8px;
        background: linear-gradient(to right, {SUMVEC_BLUE}, {SUMVEC_ORANGE});
    }}

    /* Body */
    h1, h2, h3, h4 {{
        font-family: 'Inter', 'Helvetica Neue', Arial, sans-serif;
        color: {DARK_NAVY};
        font-weight: 700;
        line-height: 1.25;
        margin-top: 1.4em;
        margin-bottom: 0.5em;
        page-break-after: avoid;
    }}
    h1 {{
        font-size: 22pt;
        color: {SUMVEC_BLUE};
        border-bottom: 2px solid {SUMVEC_BLUE};
        padding-bottom: 0.2em;
    }}
    h2 {{
        font-size: 16pt;
        color: {DARK_NAVY};
        border-bottom: 1px solid {SUMVEC_BLUE};
        padding-bottom: 0.15em;
    }}
    h3 {{
        font-size: 12.5pt;
        color: {SUMVEC_BLUE};
    }}
    h4 {{
        font-size: 11pt;
        color: {DARK_NAVY};
    }}

    p {{
        margin: 0 0 0.6em 0;
    }}

    a {{
        color: {SUMVEC_BLUE};
        text-decoration: none;
        word-break: break-all;
    }}

    code {{
        font-family: 'JetBrains Mono', 'SF Mono', Menlo, Consolas, monospace;
        font-size: 9.5pt;
        background: #f4f7fa;
        color: {DARK_NAVY};
        padding: 1px 4px;
        border-radius: 3px;
    }}
    pre {{
        font-family: 'JetBrains Mono', 'SF Mono', Menlo, Consolas, monospace;
        font-size: 9pt;
        background: #f4f7fa;
        border-left: 3px solid {SUMVEC_BLUE};
        padding: 10px 12px;
        line-height: 1.4;
        white-space: pre-wrap;
        word-wrap: break-word;
        page-break-inside: avoid;
    }}
    pre code {{
        background: none;
        padding: 0;
    }}

    blockquote {{
        border-left: 3px solid {SUMVEC_ORANGE};
        padding: 4px 12px;
        color: {DARK_NAVY};
        background: #fff8f0;
        margin: 0.6em 0;
    }}

    ul, ol {{
        margin: 0.4em 0 0.8em 0;
        padding-left: 1.4em;
    }}
    li {{
        margin-bottom: 0.25em;
    }}

    table {{
        border-collapse: collapse;
        width: 100%;
        margin: 1em 0;
        font-size: 9.5pt;
        page-break-inside: avoid;
    }}
    th, td {{
        border: 1px solid #d8e0e7;
        padding: 6px 8px;
        text-align: left;
        vertical-align: top;
    }}
    th {{
        background: {SUMVEC_BLUE};
        color: #ffffff;
        font-weight: 600;
        font-size: 9pt;
        letter-spacing: 0.02em;
    }}
    tr:nth-child(even) td {{
        background: #f4f7fa;
    }}

    hr {{
        border: none;
        border-top: 1px solid #d8e0e7;
        margin: 1.5em 0;
    }}

    .footer-note {{
        margin-top: 16mm;
        padding-top: 6mm;
        border-top: 1px solid #d8e0e7;
        font-size: 9pt;
        color: {WARM_GRAY};
    }}
    """

    cover_html = f"""
    <div class="cover">
        <div class="accent-bar"></div>
        {logo_block}
        <div class="eyebrow">AI Search Optimization Audit</div>
        <h1 class="title">{_html_escape(_extract_title(md_text))}</h1>
        <div class="target">{_html_escape(target_url)}</div>
        <div class="meta">
            <div class="row"><span class="label">Generated</span><span>{generated_at.strftime("%Y-%m-%d · %H:%M %Z").strip()}</span></div>
            <div class="row"><span class="label">Auditor</span><span>ai-search-optimization · Sumvec.AI</span></div>
            <div class="row"><span class="label">Reference</span><span>developers.google.com/search/docs/fundamentals/ai-optimization-guide</span></div>
        </div>
    </div>
    """

    footer_html = """
    <div class="footer-note">
        This audit cites Google's AI Optimization Guide directly for every Google-attributed
        recommendation and labels everything else <code>[Industry practice]</code>. The Sumvec
        plugin re-verifies the canonical Google guide before each release.
    </div>
    """

    return f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<style>{css}</style>
</head>
<body>
{cover_html}
{body_html}
{footer_html}
</body>
</html>"""


def _extract_title(md_text: str) -> str:
    for line in md_text.splitlines():
        s = line.strip()
        if s.startswith("# "):
            return s[2:].strip()
    return "AI Search Optimization Audit"


def _html_escape(s: str) -> str:
    return (
        s.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def _logo_as_data_uri(logo_path: Path | None) -> str | None:
    if not logo_path:
        return None
    try:
        svg = logo_path.read_text(encoding="utf-8")
    except OSError:
        return None
    import base64

    b64 = base64.b64encode(svg.encode("utf-8")).decode("ascii")
    return f"data:image/svg+xml;base64,{b64}"


def _default_output_path(md_path: Path, host: str, generated_at: dt.datetime) -> Path:
    stamp = generated_at.strftime("%Y-%m-%d-%H%M")
    return md_path.parent / f"{host}-{stamp}.pdf"


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Render an AISO audit Markdown report to a Sumvec-branded PDF."
    )
    parser.add_argument("md_path", help="Path to the audit Markdown file.")
    parser.add_argument("--out", help="Output PDF path. Default: <host>-<YYYY-MM-DD>-<HHMM>.pdf next to the input.")
    parser.add_argument("--logo", help="Path to an SVG/PNG logo. Default: bundled assets/sumvec-logo.svg.")
    parser.add_argument(
        "--target-url",
        help="The URL that was audited. Used for the cover and filename. "
        "If omitted, derived from the input filename.",
    )
    args = parser.parse_args()

    md_path = Path(args.md_path).expanduser().resolve()
    if not md_path.exists():
        print(f"[generate_pdf] Input not found: {md_path}", file=sys.stderr)
        return 1

    try:
        import markdown  # noqa: F401
        from weasyprint import HTML  # noqa: F401
    except ImportError:
        print(_missing_deps_message())
        return 0

    md_text = md_path.read_text(encoding="utf-8")
    generated_at = dt.datetime.now()

    if args.target_url:
        host = _host_from_url(args.target_url)
        target_url_display = args.target_url
    else:
        host = _derive_host_from_filename(md_path)
        target_url_display = host.replace("-", ".")

    out_path = (
        Path(args.out).expanduser().resolve()
        if args.out
        else _default_output_path(md_path, host, generated_at)
    )

    script_path = Path(__file__).resolve()
    logo_path = _resolve_logo_path(script_path, args.logo)
    logo_data_uri = _logo_as_data_uri(logo_path)

    html_str = _build_html(md_text, target_url_display, generated_at, logo_data_uri)

    from weasyprint import HTML  # local import — already verified above

    HTML(string=html_str, base_url=str(script_path.parent)).write_pdf(str(out_path))
    print(f"[generate_pdf] PDF written: {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
